apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: shippingservice
spec:
  hosts:
  - shippingservice
  http:
  - match:
    - sourceLabels:
        app: "checkoutservice"
        delay: "true"
    fault:
      delay:
        fixedDelay: 1s
        percentage:
          value: 100
    route:
      - destination:
          host: shippingservice
  - route:
    - destination:
        host: shippingservice
